name: quran
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# build by specifying --build-name and --build-number, respectively.
version: 1.1.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

# consider running `flutter pub upgrade --major-versions`. Alternatively,
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # flutter_swiper_plus: ^2.0.4
  # state management
  provider: ^6.0.5
  # local storage
  shared_preferences: ^2.0.18
  # pdf
  # native_pdf_view: ^6.0.0+1
  flutter_cached_pdfview: ^0.4.1
  http: ^0.13.5
  # assets_audio_player: ^3.0.4+1
  # dotted_border: ^2.0.0+2
  hexcolor: ^3.0.1
  # percent_indicator: ^3.4.0
  sleek_circular_slider: ^2.0.1
  path_provider: ^2.0.13
  # shares and screenshots
  screenshot: ^1.3.0
  # share: ^2.0.4
  share_plus: ^6.3.1
  share_files_and_screenshot_widgets: ^1.0.6
  #
  flutter_svg: ^2.0.2
  # native spalsh screen
  flutter_native_splash: ^2.2.18
  # dates 
  hijri: ^3.0.0
  # qibah
  scrollable_positioned_list: ^0.3.5
  url_launcher: ^6.1.10
  flutter_compass: ^0.7.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  # percent_indicator: ^4.0.0
  easy_localization: ^3.0.1
  sticky_headers: ^0.3.0+2
  api_cache_manager: ^1.0.2
  # quran: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # hive_generator: ^1.1.2
  # build_runner: ^2.1.8
  flutter_lints: ^2.0.1

#   # section change app icon
#   flutter_launcher_icons: "^0.9.2"
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/logo.png"  
#  # end section change app icon

# flutter_native_splash:
#   image: assets/logo.png
#   color: "#ffffff"
  #background_image: "assets/background.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/arabic_quran/
    - assets/json/
    - assets/icons/
    - assets/pdf/
    - assets/praying_time/
    - assets/home/
    - assets/fonts/
    - assets/animation/
    - assets/translations/
    - assets/duaa_imgs/

  fonts:
    - family: Almarai
      fonts:
      - asset: assets/fonts/Almarai-Regular.ttf
      - asset: assets/fonts/Almarai-Light.ttf
      - asset: assets/fonts/Almarai-Bold.ttf
      - asset: assets/fonts/Almarai-ExtraBold.ttf


    - family: quran
      fonts:
      - asset: assets/HafsSmart_08.ttf
    - family: me_quran
      fonts:
      - asset: assets/me_quran.ttf