name: quran
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# build by specifying --build-name and --build-number, respectively.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# consider running `flutter pub upgrade --major-versions`. Alternatively,
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
   # swipper 
  flutter_swiper_plus: ^2.0.4
  # state management
  provider: ^6.0.1
  # local storage
  shared_preferences: ^2.0.9
  # pdf
  flutter_cached_pdfview: ^0.4.1
  http: ^0.13.4
  assets_audio_player: ^3.0.4+1
  # dotted_border: ^2.0.0+2
  hexcolor: ^2.0.5
  # percent_indicator: ^3.4.0
  sleek_circular_slider: ^2.0.1
  path_provider: ^2.0.8
  sqflite: ^2.0.1
  fluttertoast: ^8.0.8
  # tutorial_coach_mark: ^1.2.1
  coachmaker: ^0.1.1
  # shares and screenshots
  screenshot: ^1.2.3
  # share: ^2.0.4
  share_plus: ^3.0.4
  share_files_and_screenshot_widgets: ^1.0.6
  #  
  easy_localization: ^3.0.0
  #
  flutter_svg: ^1.0.3
  # native spalsh screen
  flutter_native_splash: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # section change app icon
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"  
 # end section change app icon

flutter_native_splash:
  image: assets/logo.png
  color: "#d4d4d4"
  #background_image: "assets/background.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/arabic_quran/
    - assets/azkar/
    - assets/json/
    - assets/pdf/
    - assets/praying_time/
    - assets/home/
    - assets/fonts/
    - assets/intro/
    - assets/translations/

  fonts:
    - family: pfd
      fonts:
        - asset: assets/fonts/PFDinTextUniversal-Medium.ttf
      # weight: 700

    - family: almarai
      fonts:
        - asset: assets/fonts/almarai.ttf
      # weight: 700
    
    - family: tajawal
      fonts:
        - asset: assets/fonts/tajawal.ttf
      # weight: 700   

    - family: cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
      # weight: 700
